name: offline_notes
description: Offline-first notes application with sync and conflict resolution.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  sqflite: ^2.4.2
  path: ^1.9.1
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  adaptive_icon_background: "#F7F5EE"
  adaptive_icon_foreground: assets/images/app_icon.png

flutter_native_splash:
  color: "#F7F5EE"
  image: assets/images/app_icon.png
  android_12:
    color: "#F7F5EE"
    image: assets/images/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
